---

name: Build this Docker image

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '11 23 * * 0'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout PHP7
        uses: actions/checkout@v2
        with:
          ref: php7
          path: php7

      - name: Checkout PHP8
        uses: actions/checkout@v2
        with:
          ref: php8
          path: php8

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push PHP7
        id: docker_build_7
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: devopsansiblede/apache:latest
          no-cache: true
          context: ./php7/
          file: ./php7/Dockerfile

      - name: Image digest PHP7
        run: echo ${{ steps.docker_build_7.outputs.digest }}

      - name: Last Build PHP7
        run: sed -i -E "s/^[0-9]{4}-[0-9]{2}-[0-9]{2}\s+[0-9]{2}:[0-9]{2}:[0-9]{2}$/$( date +"%Y-%m-%d %T" )/" ./php7/README.md

      - name: Commit last built PHP7
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Last built
          commit_user_name: GitHub Actions
          commit_user_email: dev@macwinnie.me
          repository: ./php7/

      - name: Build and push PHP8
        id: docker_build_8
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: devopsansiblede/apache:php8
          no-cache: true
          context: ./php8/
          file: ./php8/Dockerfile

      - name: Image digest PHP8
        run: echo ${{ steps.docker_build_8.outputs.digest }}

      - name: Last Build PHP8
        run: sed -i -E "s/^[0-9]{4}-[0-9]{2}-[0-9]{2}\s+[0-9]{2}:[0-9]{2}:[0-9]{2}$/$( date +"%Y-%m-%d %T" )/" ./php8/README.md

      - name: Commit last built PHP8
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Last built
          commit_user_name: GitHub Actions
          commit_user_email: dev@macwinnie.me
          repository: ./php7/



...
